#curl -XPOST -d '{"jsonrpc": "2.0", "method": "deploy", "params": {"type": 1,"chaincodeID": {"path": "github.com/hyperledger/fabric/examples/chaincode/go/contract_management","language": "GOLANG"}, "ctorMsg": { "args": ["init"] }, "metadata":[97, 115, 115, 105, 103, 110, 101, 114] ,"secureContext": "assigner"} ,"id": 0}' http://localhost:7050/chaincode

#curl -XPOST -d '{"jsonrpc": "2.0", "method": "deploy", "params": {"type": 1,"chaincodeID": {"path": "github.com/hyperledger/fabric/examples/chaincode/go/asset_management_with_roles","language": "GOLANG"}, "ctorMsg": { "args": ["init"] }, "metadata":[97, 115, 115, 105, 103, 110, 101, 114] ,"secureContext": "assigner"} ,"id": 0}' http://localhost:7050/chaincode

curl -XPOST -d '{"jsonrpc": "2.0", "method": "invoke", "params": {"type": 1, "chaincodeID": {"name": "'"$HASH"'"}, "ctorMsg":{"args": ["upload_contract","alibaba12345-56789","alibaba->lining:10000RMB,lining->alibaba:shoes10"]}, "secureContext" : "lining", "attributes":["role", "account"]}, "id":1}'  http://localhost:7050/chaincode


#curl -XPOST -d '{"jsonrpc": "2.0", "method": "query", "params": {"type": 1, "chaincodeID": {"name": "'"$HASH"'"}, "ctorMsg": {"args": ["query", "myasset"]}, "secureContext": "bob", "attributes": ["role", "account"]}, "id": 1}' http://localhost:7050/chaincode


#curl -XPOST -d '{"jsonrpc": "2.0", "method": "invoke", "params": {"type": 1, "chaincodeID": {"name": "'"$HASH"'"}, "ctorMsg": {"args": ["assign", "myasset","MIIClTCCAjugAwIBAgIRAItElprohkBauwJsJLFkdjAwCgYIKoZIzj0EAwMwMTELMAkGA1UEBhMCVVMxFDASBgNVBAoTC0h5cGVybGVkZ2VyMQwwCgYDVQQDEwN0Y2EwHhcNMTYwOTIyMTE1MjU3WhcNMTYxMjIxMTE1MjU3WjBFMQswCQYDVQQGEwJVUzEUMBIGA1UEChMLSHlwZXJsZWRnZXIxIDAeBgNVBAMTF1RyYW5zYWN0aW9uIENlcnRpZmljYXRlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEytQdXrVLcV3GJhfaec+mvLlgKblBWkGPifadHWmMC7DNTeqVAl6EF53xQzKWHxKoKNFvv7xs0Wqp082ZL0nabaOCAR4wggEaMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMA0GA1UdDgQGBAQBAgMEMA8GA1UdIwQIMAaABAECAwQwEAYGKgMEBQYKBAZjbGllbnQwGAYGKgMEBQYLBA5ib2IyMzQ1Ni02Nzg5MDBNBgYqAwQFBgcBAf8EQKUW44rWXh4+F20K04SN6ibG8KiAKjYa5o7nvd30EfDGHqDaO8ZoSFUipTIhnny2QibCuSNcYAalzGNAtZbGR3kwOgYGKgMEBQYIBDCjqSrBEbObTgoM/025st2j3Z2KqoV6MzuyaXdSxZ4BvgLK7og0xXqLjle3n8fZ2V0wIwYGKgMEBQYJBBkwMEhFQURyb2xlLT4xI2FjY291bnQtPjIjMAoGCCqGSM49BAMDA0gAMEUCIQCBKF2PvySo4J7aUnMjedYyiYQPIhPtFKjEeBCIqsJZAwIgfcgvgB/469qcLRTLHKI3hzqB7TuZI8I06F0P15xvSeg="]}, "metadata":[97, 115, 115, 105, 103, 110, 101, 114], "secureContext": "assigner", "attributes": ["role", "account"]}, "id": 1}' http://localhost:7050/chaincode
